name: AutoServerUpdater
version: '${project.version}'
main: de.tamion.AutoServerUpdater
api-version: '1.13'
load: STARTUP
authors: [Tamion]
description: Automatically updates the server to the latest build for your version
